<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentManagement.Core\DocumentManagement.Core.csproj" />
    <ProjectReference Include="..\DocumentManagement.Data\DocumentManagement.Data.csproj" />
    <ProjectReference Include="..\DocumentManagement.Models\DocumentManagement.Models.csproj" />
  </ItemGroup>

</Project>